apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring-ns
data:
  WORKSPACE_DIR: "/vol/workspace"
  WORKSPACE_DNS: "monitoring-front-service.monitoring-ns"
  WORKSPACE_PORT: "8000"

  DATABASE_HOST: "sensor-db-ha-ro.database-ns"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "sensor-db"
  DATABASE_HOST_RW: "sensor-db-ha-rw.database-ns"

  TRAINING_DNS: "ml-api-service.ml-application-ns"
  TRAINING_PORT: "80"

---

# Configuration for CronJob
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-job-config
  namespace: monitoring-job-ns
data:
  # Completion count should be the same as the number of tables
  completion_count: "4"
  parallelism_count: "4"
  # iot_pond_7,iot_pond_8,iot_pond_9 are excluded since the test dataset contains fully empty columns
  # iot_pond_6,iot_pond_10,iot_pond_11,iot_pond_12 are excluded since only the first 4 ponds contain good enough data
  tables: "iot_pond_1,iot_pond_2,iot_pond_3,iot_pond_4"  
  range: "10000"
  columns: "temperature,turbidity,dissolved_oxygen,ph,ammonia,nitrate,population,fish_length,fish_weight"
  dns: "monitoring-middle-service.monitoring-ns"
  port: "8000"