apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring-ns
data:
  WORKSPACE_DIR: "/vol/workspace"
  WORKSPACE_URL: "http://0.0.0.0:8000"
  DATABASE_DNS: "sensor-db-ha-ro.database-ns"
  DATABASE_PORT: "5432"

---

# Configuration for CronJob
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-job-config
  namespace: monitoring-ns
data:
  completion_count: "11"
  parallelism_count: "4"
  tables: "iot_pond_1,iot_pond_2,iot_pond_3,iot_pond_4,iot_pond_6,iot_pond_7,iot_pond_8,iot_pond_9,iot_pond_10,iot_pond_11,iot_pond_12"
  range: "10000"
  columns: "temperature,turbidity,dissolved_oxygen,ph,ammonia,nitrate,population,fish_length,fish_weight"
  url: "monitoring-service:8001"