apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-back-deploy
  namespace: monitoring-ns
  labels:
    app: monitoring-backapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backapp
  template:
    metadata:
      labels:
        app: monitoring-backapp
    spec:
      containers:
      - name: monitoring-backend
        image: docker.io/originaluuser/divteam_monitoring_backend:2.2
        command: [ "procrastinate" ]
        args: [ "--app=app.app", "worker" ]
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "50m"
        env:
          - name: PYTHONPATH
            value: "."
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mirror-postgres-credentials-admin
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: mirror-postgres-credentials-admin
                key: password
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: DATABASE_NAME
          - name: DATABASE_HOST_RW
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: DATABASE_PORT
          
          - name: TRAINING_DNS
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: TRAINING_DNS
          - name: TRAINING_PORT
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: TRAINING_PORT

          - name: WORKSPACE_DNS
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: WORKSPACE_DNS
          - name: WORKSPACE_PORT
            valueFrom:
              configMapKeyRef:
                name: monitoring-config
                key: WORKSPACE_PORT

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monitoring-back-app-hpa
  namespace: monitoring-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoring-back-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50