apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitoring-scheduled-job
  namespace: monitoring-job-ns
spec:
  schedule: "0 0 * * *" # Every night at midnight
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Job logs last for 1 day before getting deleted
      template:
        spec:
          serviceAccountName: job-launcher-sa
          restartPolicy: OnFailure
          containers:
          - name: launcher
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              # Obtain completions from monitoring-job-config ConfigMap (And making sure its at least 1)
              COUNT=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.completion_count}')
              if [ -z "$COUNT" ]; then COUNT=1; fi

              # Obtain parallelism from monitoring-job-config ConfigMap (And making sure its at least 1)
              PARALLELISM=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.parallelism_count}')
              if [ -z "$PARALLELISM" ]; then PARALLELISM=1; fi

              JOB_NAME="scheduled-report-job-$(date +%s)"
              echo "Launching Job $JOB_NAME with $COUNT completions..."

              # Obtain tables, range, and columns from monitoring-job-config ConfigMap
              TABLES=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.tables}')
              RANGE=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.range}')
              COLUMNS=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.columns}')

              # Obtain DNS and target port of monitoring service from ConfigMap
              MONITORING_DNS=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.dns}')
              MONITORING_PORT=$(kubectl get configmap monitoring-job-config -n monitoring-job-ns -o jsonpath='{.data.port}')

              # Create the Indexed Job 
              cat <<EOF | kubectl apply -f -
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: $JOB_NAME
                namespace: monitoring-job-ns
              spec:
                completions: $COUNT
                parallelism: $PARALLELISM
                completionMode: Indexed
                ttlSecondsAfterFinished: 86400
                template:
                  spec:
                    restartPolicy: Never
                    containers:
                    - name: worker
                      image: docker.io/originaluuser/divteam_monitoring_cronjob:0.4
                      command: ["python3", "./send-request.py"]
                      env:
                      - name: TABLES
                        value: "${TABLES}"
                      - name: RANGE
                        value: "$RANGE"
                      - name: COLUMNS
                        value: "$COLUMNS"
                      - name: MONITORING_DNS
                        value: "$MONITORING_DNS"
                      - name: MONITORING_PORT
                        value: "$MONITORING_PORT"
              EOF