# Secret for postgres db password (ml-admin user)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-ml-admin
  namespace: ml-artifacts-db-ns
  # annotations:
  #  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  #  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ml-application-ns" # Add: Inference namespace
type: kubernetes.io/basic-auth
stringData:
  # The user and password will be injected by GitHub Actions when testing
  username: "ml_admin"
  password: "${ML_POSTGRES_PASS}"