apiVersion: v1
kind: Secret
metadata:
  name: ml-user-credentials
  namespace: database-ns
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ml-application-ns"
type: kubernetes.io/basic-auth
stringData:
  username: "ml_user"
  password: "${ML_POSTGRES_PASS}"