apiVersion: batch/v1
kind: Job
metadata:
  name: ml-data-loader
  namespace: database-ns
spec:
  template:
    spec:
      containers:
      - name: loader
        image: ${UPLOAD_DATA_WORKER}
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials-admin
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials-admin
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      restartPolicy: OnFailure
  backoffLimit: 0