apiVersion: v1
kind: Secret
metadata:
 name: mirror-postgres-credentials-ml-admin
 namespace: inference-ns
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "ml-artifacts-db-ns/postgres-credentials-ml-admin"
type: kubernetes.io/basic-auth
data:
  username: ""
  password: ""