apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-trainer
  namespace: ml-application-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ml-trainer
  template:
    metadata:
      labels:
        app: ml-trainer
    spec:   
      containers:
      - name: worker
        image: ${UPLOAD_TRAINING_WORKER}
        imagePullPolicy: IfNotPresent
        env:
        - name: SENSOR_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: username
        - name: SENSOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: password
        - name: ML_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: username
        - name: ML_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: password
        - name: SENSOR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-host
        - name: ML_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-host
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  namespace: ml-application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: api
        image: ${UPLOAD_TRAINING_WORKER}
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "training_scheduler", "enable-api"]
        ports:
        - containerPort: 8000
        env:
        - name: SENSOR_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: username
        - name: SENSOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: password
        - name: ML_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: username
        - name: ML_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: password
        - name: SENSOR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-host
        - name: ML_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-host
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-application-ns
spec:
  selector:
    app: ml-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000