apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-trainer
  namespace: ml-application-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ml-trainer
  template:
    metadata:
      labels:
        app: ml-trainer
    spec:   
      containers:
      - name: worker
        image: ${UPLOAD_TRAINING_WORKER}
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: SENSOR_DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(SENSOR_DB_NAME)"
        - name: ML_DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(ML_DB_NAME)"
        - name: PYTHONPATH
          value: "."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  namespace: ml-application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: api
        image: ${UPLOAD_TRAINING_WORKER}
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "training_scheduler", "enable-api"]
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: SENSOR_DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(SENSOR_DB_NAME)"
        - name: ML_DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(ML_DB_NAME)"
        - name: PYTHONPATH
          value: "."
---
apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-application-ns
spec:
  selector:
    app: ml-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000