apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-trainer
  namespace: ml-application-ns
spec:
  selector:
    matchLabels:
      app: ml-trainer
  template:
    metadata:
      labels:
        app: ml-trainer
    spec:   
      containers:
      - name: worker
        image: 6zekiel/init-model-trainer-and-scheduler:v6
        imagePullPolicy: IfNotPresent
        command: ["procrastinate", "--app=model_trainer.app", "worker"]
        resources:
          requests:
            cpu: "100m" 
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: SENSOR_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: username
        - name: SENSOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: password
        - name: ML_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: username
        - name: ML_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: password
        - name: SENSOR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-host
        - name: ML_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-host
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
        - name: PYTHONPATH
          value: "."
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-trainer-hpa
  namespace: ml-application-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-trainer
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  namespace: ml-application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: api
        image: 6zekiel/init-model-trainer-and-scheduler:v6
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "training_scheduler", "enable-api"]
        ports:
        - containerPort: 8000
        env:
        - name: SENSOR_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: username
        - name: SENSOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-admin
              key: password
        - name: ML_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: username
        - name: ML_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: password
        - name: SENSOR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-host
        - name: ML_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-host
        - name: SENSOR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: sensor-db-name
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
        - name: PYTHONPATH
          value: "."
---
apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-application-ns
spec:
  selector:
    app: ml-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000