apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: ml-application-ns
data:
  db-host: "sensor-db-ha-rw.database-ns"
  db-port: "5432"
  sensor-db-name: "sensor-db"
  ml-db-name: "ml_artifacts"
  rows-limit: "5000"