apiVersion: batch/v1
kind: Job
metadata:
  name: ml-db-setup
  namespace: ml-application-ns
  labels:
    component: ml-db-schema-initializer
spec:
  template:
    spec:
      containers:
      - name: db-initializer
        image: 6zekiel/init-ml-db:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ML_DB_USER
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: username
        - name: ML_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mirror-postgres-credentials-ml-admin
              key: password
        - name: ML_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-host
        - name: ML_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: ml-db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: db-port
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-periodic-trigger
  namespace: ml-application-ns
  labels:
    component: ml-cronjob-initializer
spec:
  schedule: "*/10 * * * *" # Every h:n(10) minutes, where (-1>n>7 & n.dtype = int) && (-1>h>13 & h.dtype = int)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: 6zekiel/init-model_trainer_scheduler:latest
            command: ["python", "training_scheduler.py"]
            env:
            - name: SENSOR_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mirror-postgres-credentials-admin
                  key: username
            - name: SENSOR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mirror-postgres-credentials-admin
                  key: password
            - name: ML_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mirror-postgres-credentials-ml-admin
                  key: username
            - name: ML_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mirror-postgres-credentials-ml-admin
                  key: password
            - name: SENSOR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: sensor-db-host
            - name: ML_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: ml-db-host
            - name: SENSOR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: sensor-db-name
            - name: ML_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: ml-db-name
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: db-port
          restartPolicy: OnFailure