apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader
  namespace: database-ns
spec:
  template:
    spec:
      containers:
      - name: loader
        image: docker.io/originaluuser/divteam_database_upload:0.1
        command: ["/bin/bash", "./scripts/dataset_download.sh"]
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials-admin
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials-admin
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
      restartPolicy: OnFailure
  backoffLimit: 0