# MODEL INFEREENCE
# Reads latest data from database, Loads trained model, Makes inference, Returns inference

FROM python:3.12-slim-bookworm

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
