kind: Secret
apiVersion: v1
metadata:
  name: headlamp-admin
  namespace: headlamp-ns
  annotations:
    kubernetes.io/service-account.name: "headlamp-service-account"
type: kubernetes.io/service-account-token
