apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: headlamp-service-account
  namespace: headlamp-ns
roleRef:
  kind: ClusterRole
  name: headlamp-cluster-role