name: Run & Test Kuberetes Cluster

on: [push]

jobs:
  deploy-kubernetes-cluster-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up minikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: "max"
          memory: "max"

      - name: Verify cluster setup correctly
        run: kubectl get pods -A

      - name: Create env file for Makefile to work
        run: |
          cat <<EOF > .env
          POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}
          ML_POSTGRES_PASS=${{ secrets.ML_POSTGRES_PASS }}
          EOF

      - name: Set up k8s cluster
        run: |
          make
          make upload-data model-artifacts-schema
        env:
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}

      - name: Opening port for database testing
        run: |
          # Open tunnels
          kubectl port-forward svc/sensor-db-ha-rw 5432:5432 -n database-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 5432; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

      - name: Testing sensor database cluster
        uses: yakubique/query-postgresql@v1.2
        with:
          query: "SELECT * FROM iot_pond_1 LIMIT 10"
          host: 127.0.0.1
          port: 5432
          username: ${{ secrets.POSTGRES_USER }}
          password: ${{ secrets.POSTGRES_PASS }}
          db: ${{ secrets.SENSOR_DB_NAME }}
          ssl: 'false'

      - name: Testing monitoring deployment, send report generation request to API, send request to UI
        run: |
          kubectl wait --for=condition=Ready pod -l app=monitoring-frontapp --namespace=monitoring-ns --timeout=240s
          kubectl wait --for=condition=Ready pod -l app=monitoring-middleapp --namespace=monitoring-ns --timeout=240s
          sleep 30

          # Open tunnel
          kubectl port-forward svc/monitoring-front-service 8000:8000 -n monitoring-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8000; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done
          kubectl port-forward svc/monitoring-middle-service 8001:8000 -n monitoring-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8001; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

          # Report generation request
          curl -o output.json -X POST http://127.0.0.1:8001 -H "Content-Type: application/json" -d '{"table_name": "iot_pond_1"}'

          # Monitoring API request
          curl -o output.json http://127.0.0.1:8001

          # Evidently UI request, checks if the project was created successfully
          curl -o output.json http://127.0.0.1:8000/api/projects/search/Aquaponics%20Monitoring

      - name: Testing ingestion deployment, send curl to API
        run: |
          kubectl wait --for=condition=Ready pod -l app=ingestion-app --namespace=ingestion-ns --timeout=240s

          # Open tunnel
          kubectl port-forward svc/ingestion-service 8002:81 -n ingestion-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8002; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

          # Curl API to see if it exists
          curl http://127.0.0.1:8002

      - name: Testing dashboard deployment, send curl to API
        run: |
          kubectl wait --for=condition=Ready pod -l app=dashboard-app --namespace=dashboard-ns --timeout=240s

          # Open tunnel
          kubectl port-forward svc/dashboard-service 8003:8081 -n dashboard-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8003; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

          # Curl API to see if it exists
          curl http://127.0.0.1:8003

      - name: Testing training deployment, send curl to API
        run: |
          kubectl wait --for=condition=Ready pod -l app=ml-trainer --namespace=ml-application-ns --timeout=240s

          # Open tunnel
          kubectl port-forward svc/ml-api-service 8004:80 -n ml-application-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8004; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

          # Curl API to see if it exists
          curl http://127.0.0.1:8004

      - name: Testing inference deployment, send curl to API
        run: |
          kubectl wait --for=condition=Ready pod -l app=inference-app --namespace=inference-ns --timeout=240s

          # Open tunnel
          kubectl port-forward svc/inference-service 8005:85 -n inference-ns &
          for i in {1..30}; do
              if nc -z 127.0.0.1 8005; then
                  echo "Tunnel is open!"
                  break
              fi
              sleep 0.5
          done

          # Curl API to see if it exists
          curl http://127.0.0.1:8005